version: "2"
services:

  sitesearch:
    image: quay.io/giantswarm/sitesearch:6bb6daa8fd02530b319f27b0eacf84df3c785693

  content:
    image: quay.io/giantswarm/docs

  proxy:
    image: registry.giantswarm.io/giantswarm/docs-proxy
    depends_on:
     - "sitesearch"
     - content
    ports:
     - "80:80"

  indexer:
    image: quay.io/giantswarm/docs-indexer:5de9478e0404eebcc39512f25fd4b07fb9e2b327
    depends_on:
      - "sitesearch"
    environment:
      REPOSITORY_URL: https://github.com/giantswarm/docs-content.git
      REPOSITORY_BRANCH: master
      REPOSITORY_SUBFOLDER: content
      EXTERNAL_REPOSITORY_SUBFOLDER: docs
      KEEP_PROCESS_ALIVE: "True"
      ELASTICSEARCH_ENDPOINT: http://admin:e4dfbjb3rohi8qpoadsffodin@sitesearch:9200
