sitesearch:
  image: registry.giantswarm.io/giantswarm/sitesearch
  volumes:
   - sitesearch-volume-data:/data
docsslave:
  image: registry.giantswarm.io/giantswarm/docs
  environment:
    BASE_URL: http://192.168.99.100
docsmaster:
  image: registry.giantswarm.io/giantswarm/docs
  links:
   - "sitesearch"
  environment:
    BASE_URL: http://192.168.99.100
docsproxy:
  image: registry.giantswarm.io/giantswarm/docs-proxy
  links:
   - "sitesearch"
   - "docsmaster"
   - "docsslave"
  ports:
   - "80:80"
