version: "2"
services:

  content:
    image: quay.io/giantswarm/docs:latest

  sitesearch:
    image: quay.io/giantswarm/sitesearch:latest

  api-spec:
    image: quay.io/giantswarm/api-spec:latest

  proxy:
    image: quay.io/giantswarm/docs-proxy:latest
    depends_on:
      - sitesearch
      - content
      - api-spec
    volumes:
      - ./test/certificate:/etc/nginx/certs
    ports:
      - "443:8000"

  indexer:
    image: quay.io/giantswarm/docs-indexer:latest
    depends_on:
      - sitesearch
    environment:
      REPOSITORY_URL: https://github.com/giantswarm/docs-content.git
      REPOSITORY_BRANCH: master
      REPOSITORY_SUBFOLDER: content
      EXTERNAL_REPOSITORY_SUBFOLDER: docs
      KEEP_PROCESS_ALIVE: "True"
      ELASTICSEARCH_ENDPOINT: http://admin:e4dfbjb3rohi8qpoadsffodin@sitesearch:9200
