sitesearch:
  image: registry.giantswarm.io/giantswarm/sitesearch:0.3.1
  volumes:
   - sitesearch-volume-data:/data
docsslave:
  image: registry.giantswarm.io/giantswarm/docs
  environment:
    BASE_URL: http://docker.dev
docsmaster:
  image: registry.giantswarm.io/giantswarm/docs
  links:
   - "sitesearch"
  environment:
    BASE_URL: http://docker.dev
docsproxy:
  image: registry.giantswarm.io/giantswarm/docs-proxy
  links:
   - "sitesearch"
   - "docsmaster"
   - "docsslave"
  ports:
   - "80:80"
