version: "2"
services:

  content:
    image: quay.io/giantswarm/docs:dev

  sitesearch:
    image: quay.io/giantswarm/sitesearch:latest

  api-spec:
    image: quay.io/giantswarm/api-spec:latest

  proxy:
    image: registry.giantswarm.io/giantswarm/docs-proxy
    depends_on:
      - sitesearch
      - content
      - api-spec
    ports:
     - "80:80"

  indexer:
    image: quay.io/giantswarm/docs-indexer:latest
    depends_on:
      - sitesearch
    environment:
      REPOSITORY_URL: https://github.com/giantswarm/docs-content.git
      REPOSITORY_BRANCH: master
      REPOSITORY_SUBFOLDER: content
      EXTERNAL_REPOSITORY_SUBFOLDER: docs
      KEEP_PROCESS_ALIVE: "True"
      ELASTICSEARCH_ENDPOINT: http://admin:e4dfbjb3rohi8qpoadsffodin@sitesearch:9200
