site_name: Giant Swarm Docs

dev_addr: '0.0.0.0:8000'

docs_dir: sources


pages:
# Introduction
- ['index.md', 'Welcome']

# Installation
- ['installation/cheatsheet.md', 'Installation', 'Cheatsheet']
- ['installation/gettingstarted.md', 'Installation', 'Getting Started']

# Guides
- ['guides/index.md', 'Guides']

# Reference
- ['reference/index.md', 'Reference']
