site_name: Giant Swarm Docs

dev_addr: '0.0.0.0:8000'

docs_dir: sources

theme_dir: ./theme/giantswarm/

pages:
# Introduction
- ['index.md', 'Welcome']

# Installation
- ['installation/cheatsheet.md', 'Installation', 'Cheat Sheet']
- ['installation/whatisgiantswarm.md', 'Installation', 'What is Giant Swarm?']
- ['installation/gettingstarted.md', 'Installation', 'Getting Started - Part 1']
- ['installation/gettingstarted2.md', 'Installation', 'Getting Started - Part 2']

# Guides
- ['guides/ruby_on_rails.md', 'Guides', 'Rails']
- ['guides/symfony.md', 'Guides', 'PHP and Symfony']
- ['guides/python.md', 'Guides', 'Python']
- ['guides/java.md', 'Guides', 'Java']

# Reference
- ['reference/index.md', 'Reference', 'Overview']
- ['reference/global-options.md', 'Reference', 'Global options']
- ['reference/info.md', 'Reference', 'Getting basic information']
- ['reference/companies.md', 'Reference', 'Companies']
- ['reference/env.md', 'Reference', 'Environments']
- ['reference/swarm-json.md', 'Reference', 'Application configuration (swarm.json)']
- ['reference/up.md', 'Reference', 'Creating and starting an app']
- ['reference/create.md', 'Reference', 'Creating an app']
- ['reference/start.md', 'Reference', 'Starting an app or service']
- ['reference/stop.md', 'Reference', 'Stopping an app or service']
- ['reference/ls.md', 'Reference', 'Listing applications']
- ['reference/status.md', 'Reference', 'Getting status information']
- ['reference/stats.md', 'Reference', 'Getting instance statistics']
- ['reference/scaleup.md', 'Reference', 'Scaling up a component']
- ['reference/scaledown.md', 'Reference', 'Scaling down a component']
- ['reference/logs.md', 'Reference', 'Accessing process logs']
- ['reference/user.md', 'Reference', 'Modifying user settings']
- ['reference/registry.md', 'Reference', 'Using the registry']

# Search
- ['search.md', 'Search']
