baseurl = "http://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false

[Blackfriday]
    plainIdAnchors = true

[[menu.main]]
    name = "Introduction"
    url = "/introduction/"
    weight = 20
[[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
