apiVersion: batch/v1
kind: Job
metadata:
  namespace: docs
  name: docs-indexer
spec:
  template:
    metadata:
      name: docs-indexer
      labels:
        app: docs
        component: docs-indexer
    spec:
      containers:
      - name: docs-indexer
        image: quay.io/giantswarm/docs-indexer:e5b2cb7ad5c1acdf5d2cfeefe6149bcd36f8fe80
        env:
          - name: ELASTICSEARCH_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: elasticsearch-endpoint-url
                key: value
          - name: EXTERNAL_REPOSITORY_SUBFOLDER
            value: docs
          - name: REPOSITORY_BRANCH
            value: master
          - name: REPOSITORY_SUBFOLDER
            value: content
          - name: REPOSITORY_URL
            value: https://github.com/giantswarm/docs-content.git
      restartPolicy: OnFailure
      # retry for a maximum of 10 minutes
      activeDeadlineSeconds: 600
