baseurl = "https://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false

[taxonomies]
    tag = "tags"

[Blackfriday]
    plainIdAnchors = true

[[menu.main]]
    name = "Basics"
    url = "/basics/"
    weight = 20
[[menu.main]]
    name = "User Guides"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
[[menu.main]]
    name = "Changelog"
    url = "/changelog/"
    weight = 50
[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 60
