apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: docs
  name: content
  labels:
    app: docs
    component: content
    repo: giantswarm/docs
spec:
  replicas: 2
  template:
    metadata:
      name: content
      labels:
        app: docs
        component: content
        repo: giantswarm/docs
    spec:
      containers:
        - image: quay.io/giantswarm/docs:[[ .SHA ]]
          name: content
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 0.2
              memory: 10M
            limits:
              cpu: 0.5
              memory: 20M
      imagePullSecrets:
        - name: docs-pull-secret
